### ISSUE TITLE
DoH/DoH-over-QUIC always crashing

### ISSUE THREAD

**Issue by galpt** [folbricht/routedns#127]
Hello,
Whenever we try to use DoH-over-QUIC, it crashed after running sometime.
When started, everything seems to be fine but for longtime usage it gives us errors.

It's always happening whenever we're using DoH-over-QUIC as an upstream/listener server/client.
Using DoQ directly is quite stable until now, but we wanted to receive all of QUIC benefits by using DoH-over-QUIC as upstream resolvers.

Here's the upstream config we're using:
```
# Google DNS-over-HTTP with bootstrapping to avoid initial lookup
[resolvers.google-doh-post-bootstrap]
address = "https://dns.google/dns-query"
protocol = "doh"
transport = "quic"
bootstrap-address = "8.8.8.8"
```

These are the errors after running it for a couple of minutes or hours:
**Error 1**
```
time="2021-01-28T18:03:33+07:00" level=info msg="starting listener" addr=":443" id=server protocol=doq
time="2021-01-28T21:15:13+07:00" level=error msg="failed to resolve" addr=":443" client="127.0.0.1:49820" error="Post \"https://dns.google/dns-query\": listen udp :0: bind: An attempt was made to access a socket in a way forbidden by its access permissions." id=server protocol=doq qname=mtalk.google.com.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x689f19]
```

**Error 2**
```
goroutine 16282 [running]:
github.com/folbricht/routedns.(*quicSession).OpenStreamSync(0xc00018fab0, 0x9401c0, 0xc0000a2010, 0x0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:301 +0x99
github.com/lucas-clemente/quic-go/http3.(*client).RoundTrip(0xc000220300, 0xc0007d6a00, 0xe, 0x0, 0x21225644128)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/client.go:184 +0x2e5
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTripOpt(0xc00006e540, 0xc0007d6a00, 0x21225c60c00, 0x30, 0x21225b7aa00, 0x150)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:112 +0x512
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTrip(0xc00006e540, 0xc0007d6a00, 0xc00006e540, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:117 +0x45
net/http.send(0xc0007d6a00, 0x930f00, 0xc00006e540, 0x0, 0x0, 0x0, 0xc000882100, 0x2030001, 0x1, 0x0)
        D:/Program Files/Go/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00007ede0, 0xc0007d6a00, 0x0, 0x0, 0x0, 0xc000882100, 0x0, 0x1, 0x4)
        D:/Program Files/Go/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00007ede0, 0xc0007d6a00, 0x0, 0x0, 0x0)
        D:/Program Files/Go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        D:/Program Files/Go/src/net/http/client.go:586
github.com/folbricht/routedns.(*DoHClient).ResolvePOST(0xc00019c360, 0xc0003ccbd0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:137 +0x33c
github.com/folbricht/routedns.(*DoHClient).Resolve(0xc00019c360, 0xc0003ccbd0, 0xc0000c0e4c, 0x10, 0x10, 0x10, 0xc0007816c0, 0xd7ed1345)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:109 +0x3cd
github.com/folbricht/routedns.(*Cache).Resolve(0xc0000700a0, 0xc0003ccbd0, 0xc0000c0e4c, 0x10, 0x10, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/cache.go:98 +0x2a7
github.com/folbricht/routedns.DoQListener.handleStream(0xc000188126, 0x6, 0xc00002a1b0, 0x4, 0x9376c0, 0xc0000700a0, 0x0, 0x0, 0x0, 0xc000059200, ...)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:178 +0x60d
github.com/folbricht/routedns.DoQListener.handleSession.func1(0xc000188126, 0x6, 0xc00002a1b0, 0x4, 0x9376c0, 0xc0000700a0, 0x0, 0x0, 0x0, 0xc000059200, ...)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:133 +0xba
created by github.com/folbricht/routedns.DoQListener.handleSession
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:132 +0x3e8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x689f19]
```

**Error 3**
```
goroutine 16281 [running]:
github.com/folbricht/routedns.(*quicSession).OpenStreamSync(0xc00018fab0, 0x9401c0, 0xc0000a2010, 0x0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:301 +0x99
github.com/lucas-clemente/quic-go/http3.(*client).RoundTrip(0xc000220300, 0xc000784700, 0xe, 0x0, 0x21225644128)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/client.go:184 +0x2e5
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTripOpt(0xc00006e540, 0xc000784700, 0x21225640c00, 0x30, 0x21225b7e470, 0x150)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:112 +0x512
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTrip(0xc00006e540, 0xc000784700, 0xc00006e540, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:117 +0x45
net/http.send(0xc000784700, 0x930f00, 0xc00006e540, 0x0, 0x0, 0x0, 0xc0000d25f0, 0x2030000, 0x1, 0x0)
        D:/Program Files/Go/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00007ede0, 0xc000784700, 0x0, 0x0, 0x0, 0xc0000d25f0, 0x0, 0x1, 0x4)
        D:/Program Files/Go/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00007ede0, 0xc000784700, 0x0, 0x0, 0x0)
        D:/Program Files/Go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        D:/Program Files/Go/src/net/http/client.go:586
github.com/folbricht/routedns.(*DoHClient).ResolvePOST(0xc00019c360, 0xc000240990, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:137 +0x33c
github.com/folbricht/routedns.(*DoHClient).Resolve(0xc00019c360, 0xc000240990, 0xc0000c0e4c, 0x10, 0x10, 0x10, 0xc000442770, 0xa256adb9)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:109 +0x3cd
github.com/folbricht/routedns.(*Cache).Resolve(0xc0000700a0, 0xc000240990, 0xc0000c0e4c, 0x10, 0x10, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/cache.go:98 +0x2a7
github.com/folbricht/routedns.DoQListener.handleStream(0xc000188126, 0x6, 0xc00002a1b0, 0x4, 0x9376c0, 0xc0000700a0, 0x0, 0x0, 0x0, 0xc000059200, ...)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:178 +0x60d
github.com/folbricht/routedns.DoQListener.handleSession.func1(0xc000188126, 0x6, 0xc00002a1b0, 0x4, 0x9376c0, 0xc0000700a0, 0x0, 0x0, 0x0, 0xc000059200, ...)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:133 +0xba
created by github.com/folbricht/routedns.DoQListener.handleSession
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/doqlistener.go:132 +0x3e8
```

**Comment by folbricht** [comment]
I'll take a look at this the next couple days. There seem to be two issues, one is of course the error itself, and the other is the fact that it triggers a panic.

**Comment by galpt** [comment]
> I'll take a look at this the next couple days. There seem to be two issues, one is of course the error itself, and the other is the fact that it triggers a panic.

Thanks! We look forward to hearing from you.

**Comment by folbricht** [comment]
The issue seems to originate in the QUIC library routedns is using. Unfortunately I can't repro it here, this may be Windows-specific. @galpt Would you be able to build from the `issue-127` branch and trigger the problem again? It will no longer panic, but should instead show a new error (should look like `... returned (nil,nil)`. I'll need to see what exactly that error says, it'll point to the source of the problem. This will help confirm if it comes from the library or not.

**Comment by galpt** [comment]
We've tried to rebuilt the **dohclient.go** using the #127 commit above and updated all the required packages (Go & other third-party packages) to the latest version but still got errors. Not sure why but the panic runtime error is still there.

**Here's the config we're using**
```
[resolvers.google]
address = "https://dns.google/dns-query"
protocol = "doh"
transport = "quic"
bootstrap-address = "8.8.8.8"

[groups.cache]
type = "cache"
resolvers = ["google"]

[listeners.any-udp]
address = ":53"
protocol = "udp"
resolver = "cache"

[listeners.any-tcp]
address = ":53"
protocol = "tcp"
resolver = "cache"
```

**These are the errors we've encountered**
```
time="2021-01-31T04:18:10+07:00" level=info msg="starting listener" addr=":53" id=any-tcp protocol=tcp
time="2021-01-31T04:18:10+07:00" level=info msg="starting listener" addr=":53" id=any-udp protocol=udp
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0xddae99]

goroutine 3200 [running]:
github.com/folbricht/routedns.(*quicSession).OpenStreamSync(0xc0002c6bd0, 0x1091a60, 0xc0000a2010, 0x0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:304 +0x99
github.com/lucas-clemente/quic-go/http3.(*client).RoundTrip(0xc000188080, 0xc00013e900, 0xe, 0x0, 0x14ced9b00b0)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/client.go:184 +0x2e5
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTripOpt(0xc0000d5d00, 0xc00013e900, 0x14ced9f1700, 0x30, 0x14ced9ba070, 0x150)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:112 +0x512
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTrip(0xc0000d5d00, 0xc00013e900, 0xc0000d5d00, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:117 +0x45
net/http.send(0xc00013e900, 0x1082740, 0xc0000d5d00, 0x0, 0x0, 0x0, 0xc0000d23e0, 0x2030001, 0x1, 0x0)
        D:/Program Files/Go/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00012f9e0, 0xc00013e900, 0x0, 0x0, 0x0, 0xc0000d23e0, 0x0, 0x1, 0x4)
        D:/Program Files/Go/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00012f9e0, 0xc00013e900, 0x0, 0x0, 0x0)
        D:/Program Files/Go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        D:/Program Files/Go/src/net/http/client.go:586
github.com/folbricht/routedns.(*DoHClient).ResolvePOST(0xc00012a750, 0xc000350bd0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:137 +0x33c
github.com/folbricht/routedns.(*DoHClient).Resolve(0xc00012a750, 0xc000350bd0, 0xc00050690c, 0x10, 0x10, 0x10, 0xc000616a80, 0x22d91cda)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:109 +0x3cd
github.com/folbricht/routedns.(*Cache).Resolve(0xc0000d6280, 0xc000350bd0, 0xc00050690c, 0x10, 0x10, 0x10, 0x1, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/cache.go:98 +0x2a7
github.com/folbricht/routedns.listenHandler.func1(0x10988c0, 0xc000386e80, 0xc000350bd0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dnslistener.go:71 +0x6d3
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0001169a0, 0x10988c0, 0xc000386e80, 0xc000350bd0)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:37 +0x4b
github.com/miekg/dns.(*Server).serveDNS(0xc0000d9e60, 0xc0006e4000, 0x2a, 0x200, 0xc000386e80)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:650 +0x2f7
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0000d9e60, 0xc00002a080, 0xc0006e4000, 0x2a, 0x200, 0x1096280, 0xc000006018, 0xc0000d2348, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:590 +0xf4
created by github.com/miekg/dns.(*Server).serveUDP
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:520 +0x387

```

**Comment by folbricht** [comment]
ahh, thank you. That actually helped. Pretty sure the panic is fixed now (on the same branch). Could you try again? I suspect the panic was hiding the underlying error, so that should show up now.

**Comment by galpt** [comment]
Sure. We've tried to rebuilt the **dohclient.go** using the #127 commit above, using the same **toml** configuration and ran it until it stopped working.

**These are the errors we've encountered**
```
time="2021-01-31T06:26:43+07:00" level=info msg="starting listener" addr=":53" id=any-tcp protocol=tcp
time="2021-01-31T06:26:43+07:00" level=info msg="starting listener" addr=":53" id=any-udp protocol=udp
time="2021-01-31T06:57:48+07:00" level=error msg="failed to resolve" addr=":53" client="::1" error="Post \"https://dns.google/dns-query\": listen udp :0: bind: An attempt was made to access a socket in a way forbidden by its access permissions." id=any-udp protocol=udp qname=github.com.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x96ae99]

goroutine 2148 [running]:
github.com/folbricht/routedns.(*quicSession).OpenStreamSync(0xc0002a91f0, 0xc21a60, 0xc00002a038, 0x0, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:304 +0x99
github.com/lucas-clemente/quic-go/http3.(*client).RoundTrip(0xc00019a080, 0xc00035e200, 0xe, 0x0, 0x1e0a95c3340)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/client.go:184 +0x2e5
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTripOpt(0xc0000ba6c0, 0xc00035e200, 0x1e0a9982a00, 0x30, 0x1e0a95f3638, 0x150)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:112 +0x512
github.com/lucas-clemente/quic-go/http3.(*RoundTripper).RoundTrip(0xc0000ba6c0, 0xc00035e200, 0xc0000ba6c0, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/http3/roundtrip.go:117 +0x45
net/http.send(0xc00035e200, 0xc12740, 0xc0000ba6c0, 0x0, 0x0, 0x0, 0xc0000960e0, 0x2030000, 0x1, 0x0)
        D:/Program Files/Go/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00009f230, 0xc00035e200, 0x0, 0x0, 0x0, 0xc0000960e0, 0x0, 0x1, 0x4)
        D:/Program Files/Go/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00009f230, 0xc00035e200, 0x0, 0x0, 0x0)
        D:/Program Files/Go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        D:/Program Files/Go/src/net/http/client.go:586
github.com/folbricht/routedns.(*DoHClient).ResolvePOST(0xc0000c8360, 0xc0006ea480, 0x0, 0x0, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:137 +0x33c
github.com/folbricht/routedns.(*DoHClient).Resolve(0xc0000c8360, 0xc0006ea480, 0xc00037888c, 0x10, 0x10, 0x10, 0xc00041a4d0, 0x8a4c8ebb)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dohclient.go:109 +0x3cd
github.com/folbricht/routedns.(*Cache).Resolve(0xc0000ae050, 0xc0006ea480, 0xc00037888c, 0x10, 0x10, 0x10, 0x1, 0x0)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/cache.go:98 +0x2a7
github.com/folbricht/routedns.listenHandler.func1(0xc288c0, 0xc000458600, 0xc0006ea480)
        E:/galpt/Software/DNSCrypt/DNS-over-QUIC/routedns/dnslistener.go:71 +0x6d3
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0000b21c0, 0xc288c0, 0xc000458600, 0xc0006ea480)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:37 +0x4b
github.com/miekg/dns.(*Server).serveDNS(0xc0000b4ea0, 0xc000208200, 0x1c, 0x200, 0xc000458600)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:650 +0x2f7
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0000b4ea0, 0xc00002b660, 0xc000208200, 0x1c, 0x200, 0xc26280, 0xc000006530, 0xc0000063f0, 0x0, 0x0)
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:590 +0xf4
created by github.com/miekg/dns.(*Server).serveUDP
        C:/Users/galih/go/pkg/mod/github.com/miekg/dns@v1.1.37/server.go:520 +0x387
```

**Comment by galpt** [comment]
```
time="2021-01-31T07:16:59+07:00" level=info msg="starting listener" addr=":53" id=any-tcp protocol=tcp
time="2021-01-31T07:16:59+07:00" level=info msg="starting listener" addr=":53" id=any-udp protocol=udp
```

It seems the problem's solved. Started from 07:16 and still running until now — no errors encountered yet.
We'll try using different config and update you with the results later. Thanks in advance.

**Comment by folbricht** [comment]
Thank you. Though the underlying error that triggered it all shouldn't have been addressed by my fix. `An attempt was made to access a socket in a way forbidden by its access permissions` is some sort of Windows-specific issue. Looking around for the message suggests perhaps permissions of some kind.

At least it'll no longer panic/crash when that happens. Merged the fix in https://github.com/folbricht/routedns/pull/129
