### ISSUE TITLE
crash: Branch issue-229 

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#305]
@folbricht I'm not sure what this means but just wanted to let you know
```
panic: close of closed channel

goroutine 13511 [running]:
github.com/folbricht/routedns.(*request).markDone(...)
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230501081819-3500d3702c73/pipeline.go:225
github.com/folbricht/routedns.(*Pipeline).start.func2()
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230501081819-3500d3702c73/pipeline.go:109 +0x2d5
created by github.com/folbricht/routedns.(*Pipeline).start
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230501081819-3500d3702c73/pipeline.go:101 +0x498
```

**Comment by folbricht** [comment]
Interesting. Do you see this a lot? Is it reproducible? Definitely a thing I need to fix once I understand how it's happening.

**Comment by charlieporth1** [comment]
Issue is not happaing

**Comment by cbuijs** [comment]
No problemos here after running for some days now.
